language: php

php:
  - 7.0
  - 7.1
  - 7.2
  # - nightly

matrix:
  exclude:
    # - php: 7.0
    #   env: TYPO3_VERSION="^9.0"
    - php: 7.0
      env: TYPO3_VERSION="^9.1"
    # - php: 7.1
    #   env: TYPO3_VERSION="^9.0"
    - php: 7.1
      env: TYPO3_VERSION="^9.1"
    - php: nightly
      env: TYPO3_VERSION="^8.7"
  allow_failures:
    - php: nightly

env:
  global:
    - TYPO3_PATH_ROOT=$TRAVIS_BUILD_DIR/.Build
  matrix:
    - TYPO3_VERSION="^8.7"
    # - TYPO3_VERSION="^9.0"
    - TYPO3_VERSION="^9.1"

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache
    - $TRAVIS_BUILD_DIR/.Build/cache

install:
  - composer diagnose || true
  - composer validate
  - composer run:require-typo3-version "$TYPO3_VERSION"
  - git checkout .
  - composer check-platform-reqs

script:
  - composer -v --timeout=600 run-script run:test-coverage
  - composer -v --timeout=600 run-script run:parallel-test-functional
  - composer -v run:cs-lint
  - composer -v run:security-check-bugfix-for-travis

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    on_success: always
    on_failure: always
    secure: v/fPxDaYWh/iLOPB3OMgKsnF1MyNDVq5kTHf50/0iRPRQRnWBDSVIGc8fEqTX/X4gRChC7V/cwqHYfwL9RL565TJ+b/3Q7MkppGd1E6VRK5YhDiNARBUiLEGOzoHdKSLoqyHPPjALoRODzTk1icLZ+50NEfuO+mAj2EHgbsThWnx7GbOKxQLR5+zQhFbQQA/lsSWMQTbx1g+uYooy3+Qf2bbkUICGK9z9AC5EYCR4UB5WS1uWM8Bfuj725vwyuqlWqftQVrrXi/mg3oRdvSAD/o8ESgviYHkUo/5Yv+9Y/xlyq8/XUg57zGeB976dXWJZjkJkraJCVTPQwfilI/pPZooLaoECnxMZOLz8Bry3/WI749ANoAjaFNI/VQdjgY5SsRqefrTqUUtWyiaOzS/imr5YQRjqQLluQ+No5dY03rSXg2vtxvtMHitN5pu02eq/dEDh61RQAWNoaPIqymD0p+fow41KoIfT4iTTydwe+sFossm9+fOBLt/vinZ/LffZspG8MMSmny0S7rzALkH8C18UFnklt/8jYKfYFOktAVVQbgEmw4rzmGzdUy2RXR118TPuaAI5KFiu1Y/Eb0B8G0P+61L/7L2MAyytZGK6QLYB9tbF01BZabeNzDdA8P5SCQNM+ikbhYZe9WEFdRtZZWMDqd3vEpZufEFgkUJl40=
